--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/wizxrdx-pm-pl/ChunkBorders
build-by-default: true
branches:
- master
projects:
  ChunkBorders:
    path: ""
    libs:
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^2.1.0
      - src: CortexPE/Commando/Commando
        version: ^2.1.1
    lint:
      phpstan: true
...